# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TUFD_development
  username: postgres
  password: macnolo
  host: localhost
  port: 5432

production:
  <<: *default
  database: devjjac2d6lt0l
  username: bzotnpnforkxve
  password: 6b76c83746b110ca075210e0861f0341ca7d877b434d5089f4740e85a2ca61cd
  host: ec2-52-44-166-58.compute-1.amazonaws.com
  port: 5432
